name: build

on:
  push:
    paths-ignore:
    - 'doc/**'
    - '**/*.md'
    - 'README.md'
  schedule:
  - cron: "0 0 * * *"

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache
      id: cache
      uses: actions/cache@v2
      with:
        path: _install
        key: windows-v2-${{ hashFiles('VERSIONS') }}
        restore-keys: |
          windows-v2-
    - name: install_tools.ps1
      run: "& .\\install_tools.ps1"
    - name: cmake.ps1
      run: "& .\\cmake.ps1"
    - name: Copy Windows files
      run: |
        mkdir windows
        Copy-Item build\Release\SoraUnitySdk.dll windows
        Copy-Item _install\webrtc\NOTICE windows
    - name: Upload Windows Artifact
      uses: actions/upload-artifact@v2
      with:
        name: windows
        path: windows
  build-macos:
    strategy:
      fail-fast: false
      matrix:
        name:
          - macos
          - ios
          # Android に関しては多分 Ubuntu でもいけると思うけど、
          # 普段ビルドしてるのは macOS からなので macOS でビルドする
          - android
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache
      id: cache
      uses: actions/cache@v2
      with:
        path: _install
        key: macos-v1-${{ hashFiles('VERSIONS') }}
        restore-keys: |
          macos-v1-
    - name: install_tools.sh
      run: ./install_tools.sh
    - name: cmake.sh
      run: ./cmake.sh ${{ matrix.name }}
    # macOS 用
    - name: Copy macOS files
      if: matrix.name == 'macos'
      run: |
        mkdir macos/
        cp -r _build/sora-unity-sdk/macos/SoraUnitySdk.bundle/ macos/SoraUnitySdk.bundle/
        cp _install/macos/webrtc/NOTICE macos/
    - name: Upload macOS Artifact
      if: matrix.name == 'macos'
      uses: actions/upload-artifact@v2
      with:
        name: macos
        path: macos/
    # Android 用
    - name: Copy Android files
      if: matrix.name == 'android'
      run: |
        mkdir android/
        cp _install/android/webrtc/NOTICE android/
        cp _install/android/webrtc/jar/webrtc.jar android/
        cp _build/sora-unity-sdk/android/libSoraUnitySdk.so android/
    - name: Upload Android Artifact
      if: matrix.name == 'android'
      uses: actions/upload-artifact@v2
      with:
        name: android
        path: android/
    # iOS 用
    - name: Copy iOS files
      if: matrix.name == 'ios'
      run: |
        mkdir ios/
        cp _install/ios/webrtc/NOTICE ios/
        cp _install/ios/webrtc/lib/libwebrtc.a ios/
        cp _build/sora-unity-sdk/ios/libSoraUnitySdk.a ios/
    - name: Upload iOS Artifact
      if: matrix.name == 'ios'
      uses: actions/upload-artifact@v2
      with:
        name: ios
        path: ios/
  package:
    runs-on: macOS-latest
    needs: [build-windows, build-macos]
    steps:
    - uses: actions/checkout@v2
    - name: Download artifacts
      uses: actions/download-artifact@v2
    - name: Packaging
      run: |
        set -ex
        mkdir -p SoraUnitySdk/Plugins/SoraUnitySdk/windows/x86_64
        mkdir -p SoraUnitySdk/Plugins/SoraUnitySdk/macos
        mkdir -p SoraUnitySdk/Plugins/SoraUnitySdk/ios
        mkdir -p SoraUnitySdk/Plugins/SoraUnitySdk/android/arm64-v8a
        cp -r Sora/ SoraUnitySdk/SoraUnitySdk/
        cp windows/SoraUnitySdk.dll SoraUnitySdk/Plugins/SoraUnitySdk/windows/x86_64/
        cp -r macos/SoraUnitySdk.bundle SoraUnitySdk/Plugins/SoraUnitySdk/macos/SoraUnitySdk.bundle
        cp android/libSoraUnitySdk.so SoraUnitySdk/Plugins/SoraUnitySdk/android/arm64-v8a/
        cp android/webrtc.jar SoraUnitySdk/Plugins/SoraUnitySdk/android/
        cp ios/libSoraUnitySdk.a SoraUnitySdk/Plugins/SoraUnitySdk/ios/
        cp ios/libwebrtc.a SoraUnitySdk/Plugins/SoraUnitySdk/ios/

        cp LICENSE SoraUnitySdk/

        # NOTICE ファイルを結合する
        cp NOTICE.md SoraUnitySdk/NOTICE
        echo ""
        echo "-----------------------------" >> SoraUnitySdk/NOTICE
        echo "# WebRTC for Windows" >> SoraUnitySdk/NOTICE
        echo "-----------------------------" >> SoraUnitySdk/NOTICE
        cat windows/NOTICE >> SoraUnitySdk/NOTICE

        echo "-----------------------------" >> SoraUnitySdk/NOTICE
        echo "# WebRTC for macOS" >> SoraUnitySdk/NOTICE
        echo "-----------------------------" >> SoraUnitySdk/NOTICE
        cat macos/NOTICE >> SoraUnitySdk/NOTICE

        echo "-----------------------------" >> SoraUnitySdk/NOTICE
        echo "# WebRTC for Android" >> SoraUnitySdk/NOTICE
        echo "-----------------------------" >> SoraUnitySdk/NOTICE
        cat android/NOTICE >> SoraUnitySdk/NOTICE

        echo "-----------------------------" >> SoraUnitySdk/NOTICE
        echo "# WebRTC for iOS" >> SoraUnitySdk/NOTICE
        echo "-----------------------------" >> SoraUnitySdk/NOTICE
        cat ios/NOTICE >> SoraUnitySdk/NOTICE

    - name: Upload SoraUnitySdk
      uses: actions/upload-artifact@v2
      with:
        name: SoraUnitySdk
        path: SoraUnitySdk
  release:
    name: Upload Release Asset
    if: contains(github.ref, 'tags/202')
    needs: [package]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Download SoraUnitySdk
      uses: actions/download-artifact@v2
      with:
        name: SoraUnitySdk
        path: SoraUnitySdk
    - name: Archive to zip SoraUnitySdk
      run: |
        zip -r SoraUnitySdk SoraUnitySdk
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./SoraUnitySdk.zip
        asset_name: SoraUnitySdk.zip
        asset_content_type: application/zip
